import Aura from "@primevue/themes/aura";
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  devtools: { enabled: true },
  router: {
    options: {
      // 不输出这类警告: WARN  [Vue Router warn]: No match found for location with path
      strict: false,
      // 如果你想完全禁用这些警告（不推荐）
      // silentRouteFailureWarning: true
    },
  },
  // https://tailwindcss.com/docs/guides/nuxtjs
  css: ["~/assets/css/main.css", "primeicons/primeicons.css"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  modules: ["@primevue/nuxt-module"],
  primevue: {
    options: {
      theme: {
        preset: Aura,
      },
      locale:  {
        startsWith: '开始于',
        contains: '包含',
        notContains: '不包含',
        endsWith: '结束于',
        equals: '等于',
        notEquals: '不等于',
        noFilter: '无过滤器',
        lt: '小于',
        lte: '小于等于',
        gt: '大于',
        gte: '大于等于',
        dateIs: '日期是',
        dateIsNot: '日期不是',
        dateBefore: '日期早于',
        dateAfter: '日期晚于',
        clear: '清除',
        apply: '应用',
        matchAll: '匹配所有',
        matchAny: '匹配任意',
        addRule: '添加规则',
        removeRule: '删除规则',
        accept: '接受',
        reject: '拒绝',
        choose: '选择',
        upload: '上传',
        cancel: '取消',
        completed: '已完成',
        pending: '待处理',
        fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
        dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
        dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
        dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
        monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
        monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        chooseYear: '选择年份',
        chooseMonth: '选择月份',
        chooseDate: '选择日期',
        prevDecade: '上一个十年',
        nextDecade: '下一个十年',
        prevYear: '上一年',
        nextYear: '下一年',
        prevMonth: '上个月',
        nextMonth: '下个月',
        prevHour: '上一小时',
        nextHour: '下一小时',
        prevMinute: '上一分钟',
        nextMinute: '下一分钟',
        prevSecond: '上一秒',
        nextSecond: '下一秒',
        am: '上午',
        pm: '下午',
        today: '今天',
        weekHeader: '周',
        firstDayOfWeek: 0,
        showMonthAfterYear: true,
        dateFormat: 'yy-mm-dd',
        weak: '弱',
        medium: '中',
        strong: '强',
        passwordPrompt: '请输入密码',
        emptyFilterMessage: '无可用选项',
        searchMessage: '{0} 个结果可用',
        selectionMessage: '已选择 {0} 项',
        emptySelectionMessage: '未选择任何项',
        emptySearchMessage: '未找到结果',
        emptyMessage: '无可用选项',
        fileChosenMessage: '已选择 {0} 个文件',
        noFileChosenMessage: '未选择文件',
        aria: {
          trueLabel: '是',
          falseLabel: '否',
          nullLabel: '未选择',
          star: '1 星',
          stars: '{star} 星',
          selectAll: '选择所有',
          unselectAll: '取消选择所有',
          close: '关闭',
          previous: '上一个',
          next: '下一个',
          navigation: '导航',
          scrollTop: '滚动到顶部',
          moveTop: '移到顶部',
          moveUp: '向上移动',
          moveDown: '向下移动',
          moveBottom: '移到底部',
          moveToTarget: '移动到目标',
          moveToSource: '移动到源',
          moveAllToTarget: '全部移动到目标',
          moveAllToSource: '全部移动到源',
          pageLabel: '第 {page} 页',
          firstPageLabel: '第一页',
          lastPageLabel: '最后一页',
          nextPageLabel: '下一页',
          prevPageLabel: '上一页',
          rowsPerPageLabel: '每页行数',
          jumpToPageDropdownLabel: '跳转到页面下拉菜单',
          jumpToPageInputLabel: '跳转到页面输入',
          selectRow: '选择行',
          unselectRow: '取消选择行',
          expandRow: '展开行',
          collapseRow: '折叠行',
          showFilterMenu: '显示过滤菜单',
          hideFilterMenu: '隐藏过滤菜单',
          filterOperator: '过滤操作符',
          filterConstraint: '过滤约束',
          editRow: '编辑行',
          saveEdit: '保存编辑',
          cancelEdit: '取消编辑',
          listView: '列表视图',
          gridView: '网格视图',
          slide: '滑动',
          slideNumber: '{slideNumber}',
          zoomImage: '缩放图片',
          zoomIn: '放大',
          zoomOut: '缩小',
          rotateRight: '向右旋转',
          rotateLeft: '向左旋转'
        }
      },
    },
  },
});
